name: build_actions

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive

      # Install dependencies
      - name: Install toolchain
        run: |
          sudo apt install -y bc bison flex libssl-dev make git zip llvm lld gcc-aarch64-linux-gnu

      - name: Download Clang 12.0.7
        run: | 
          mkdir -p $GITHUB_WORKSPACE/clang
          cd $GITHUB_WORKSPACE/clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-12.0.0_r1/clang-r416183b.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz 

      - name: Export Clang 12.0.7
        run: | 
          echo "PATH=$GITHUB_WORKSPACE/clang/bin:$PATH" >> $GITHUB_ENV
          echo "CLANG_PATH=$GITHUB_WORKSPACE/clang" >> $GITHUB_ENV
      
      # Make script executable
      - name: Make build script executable
        run: chmod +x ./build_actions.sh

      # Run your build script
      - name: Build kernel
        working-directory: ${{ github.workspace }}
        run: ./build_actions.sh

      # Upload final kernel zip (placed in repo root by your script)
      - name: Upload kernel zip
        uses: actions/upload-artifact@v4
        with:
          name: kernel-zip
          path: "*.zip"
